package stepdefinitions;

import org.testng.Assert;

import com.fasterxml.jackson.core.JsonProcessingException;

import org.apache.log4j.Logger;
import org.openqa.selenium.WebDriver;

import base.BasePage;
import base.BaseTest;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.mosip.testrig.apirig.utils.AdminTestUtil;
import io.mosip.testrig.apirig.utils.SecurityXSSException;
import pages.InvalidUrlPage;
import pages.LoginOptionsPage;
import utils.EsignetConfigManager;
import utils.EsignetUtil;

public class InvalidUrlStepDefinition extends AdminTestUtil {

	public WebDriver driver;
	private static final Logger logger = Logger.getLogger(InvalidUrlStepDefinition.class);
	InvalidUrlPage invalidUrlPage;
	LoginOptionsPage loginOptionsPage;

	public InvalidUrlStepDefinition(BaseTest baseTest) {
		this.driver = baseTest.getDriver();
		invalidUrlPage = new InvalidUrlPage(driver);
		loginOptionsPage = new LoginOptionsPage(driver);

	}

	@When("user modifies domain in the esignet url")
	public void userModifiesDomainInUrl() {
		if (BasePage.authorizeUrl == null) {
			throw new IllegalStateException("authorizeUrl is not set");
		}
		String invalidUrl = BasePage.authorizeUrl.replaceFirst("://[^/]+", "://invalid.mosip.net");
		try {
			driver.get(invalidUrl);
		} catch (Exception e) {
			Assert.assertTrue(e.getMessage().contains("ERR_NAME_NOT_RESOLVED"));
		}
	}

	@Then("verify this site can’t be reached error is displayed")
	public void verifySiteCantBeReachedErrorDisplayed() {
		String pageSource = driver.getPageSource();
		Assert.assertTrue(pageSource.contains("ERR_NAME_NOT_RESOLVED"), "Expected error not displayed");
	}

	@When("user modify the hash value in the esignet url")
	public void userManipulatesHashValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("#", "#invalid");
		driver.get(modifiedUrl);
	}

	@Then("verify unable to process Please try again error is displayed")
	public void verifyUnableToProcessErrorDisplayed() {
		Assert.assertTrue(invalidUrlPage.isUnableToProcessErrorDisplayed(), "Error message is not displayed");
	}

	@When("user change the language to {string} from dropdown")
	public void userChangeLanguage(String language) {
		invalidUrlPage.clickOnLanguageDropdownOption();
		loginOptionsPage.selectLanguage(language);
	}

	@Then("verify {string} message is displayed in chosen language")
	public void verifyErrorMessageChangedAsPerLanguage(String text) {
		Assert.assertTrue(invalidUrlPage.isErrorMsgLanguageChanged(text),
				"Error message language did not change to expected language");
	}

	@When("user modify the nonce value in esignet url")
	public void userModifyNonceValue() {
		if (BasePage.authorizeUrl == null) {
			throw new IllegalStateException("authorizeUrl is not set");
		}
		String modifiedUrl = BasePage.authorizeUrl.replace("#", "?nonce=invalid123#");
		driver.get(modifiedUrl);
	}

	@Then("verify user remain on same esignet page without any error")
	public void verifyUserRemainsOnEsignetPage() {
		Assert.assertTrue(invalidUrlPage.isEsignetPageRetained(), "Page doesn't retained");
	}

	@When("user remove the nonce and state value in esignet url")
	public void userRemoveNonceAndStateValue() throws JsonProcessingException, SecurityXSSException {
		String baseUrl = EsignetConfigManager.getproperty("eSignetbaseurl");
		String template = EsignetConfigManager.getproperty("authorizeUrlTemplate");
		String requestUri = EsignetUtil.generateParRequestWithoutNonceAndState();
		String updatedTemplate = template.replace("$REQUEST_URI$", requestUri);
		updatedTemplate = AdminTestUtil.replaceIdWithAutogeneratedId(updatedTemplate, "$ID:");

		String urlWithoutNonce = baseUrl + updatedTemplate;

		driver.get(urlWithoutNonce);
	}

	@When("user modify the state value in esignet url")
	public void userModifyStateValue() {
		if (BasePage.authorizeUrl == null) {
			throw new IllegalStateException("authorizeUrl is not set");
		}
		String modifiedUrl = BasePage.authorizeUrl.replace("state", "invalid");
		driver.get(modifiedUrl);
	}

	@When("user modify the login value in esignet url")
	public void userModifyLoginValue() {
		if (BasePage.authorizeUrl == null) {
			throw new IllegalStateException("authorizeUrl is not set");
		}
		String modifiedUrl = BasePage.authorizeUrl.replace("/login", "/invalid");
		driver.get(modifiedUrl);
	}

	@When("user remove the login value in esignet url")
	public void userRemoveLoginValue() {
		if (BasePage.authorizeUrl == null) {
			throw new IllegalStateException("authorizeUrl is not set");
		}
		String modifiedUrl = BasePage.authorizeUrl.replace("login", " ");
		driver.get(modifiedUrl);
	}

	@Then("verify the page you are looking for does not exist error is displayed")
	public void verifyPageDoesNotExistErrorDisplayed() {
		Assert.assertTrue(invalidUrlPage.isPageDoesNotExistErrorMsgDisplayed(), "Error message is not displayed");
	}

	String url;

	@When("user modifies authorize value in esignet url")
	public void userModifiesAuthorizeValue() throws Exception {
		String baseUrl = EsignetConfigManager.getproperty("eSignetbaseurl");
		String template = EsignetConfigManager.getproperty("authorizeUrlTemplate");
		String requestUri = EsignetUtil.generateParRequestUri();
		String updatedTemplate = template.replace("$REQUEST_URI$", requestUri);
		updatedTemplate = AdminTestUtil.replaceIdWithAutogeneratedId(updatedTemplate, "$ID:");
		url = baseUrl + updatedTemplate;

		String modifiedUrl = url.replace("/authorize", "/invalid");
		driver.get(modifiedUrl);
	}

	@When("user removes authorize value in esignet url")
	public void userRemovesAuthorizeInUrl() throws Exception {
		String baseUrl = EsignetConfigManager.getproperty("eSignetbaseurl");
		String template = EsignetConfigManager.getproperty("authorizeUrlTemplate");
		String requestUri = EsignetUtil.generateParRequestUri();
		String updatedTemplate = template.replace("$REQUEST_URI$", requestUri);
		updatedTemplate = AdminTestUtil.replaceIdWithAutogeneratedId(updatedTemplate, "$ID:");
		String url = baseUrl + updatedTemplate;

		String modifiedUrl = url.replace("authorize?", "");
		driver.get(modifiedUrl);
	}

	@Given("user relaunches esignet url")
	public void userRelaunchesEsignetUrl() {
		driver.get(BasePage.authorizeUrl);
	}

	@Then("verify user navigated to attention screen")
	public void verifyAttentionScreenDisplayed() {
		Assert.assertTrue(invalidUrlPage.isAttentionScreenDisplayed(), "Did not navigated to attention page");
	}

	@When("user modify the claims details value in esignet url")
	public void userModifyClaimsDetailsValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("claim-details", "claim-detail");
		driver.get(modifiedUrl);
	}

	@When("user remove the claim details value in signup url")
	public void userRemoveClaimDetailsValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("claim-detail", " ");
		driver.get(modifiedUrl);
	}

	@When("user modify the identity verification value in esignet url")
	public void userModifyIdentitiyVerificationValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("identity-verification", "invalid");
		driver.get(modifiedUrl);
	}

	@When("user remove the identity verification value in esignet url")
	public void userRemoveIdentitiyVerificationValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("identity-verification", " ");
		driver.get(modifiedUrl);
	}

	@When("user modify the consent value in esignet url")
	public void userModifyConsentValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("consent", "invalid");
		driver.get(modifiedUrl);
	}

	@When("user remove the consent value in esignet url")
	public void userRemoveConsentValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("consent", " ");
		driver.get(modifiedUrl);
	}

	@When("user modifies domain in the signup url")
	public void userModifiesDomainInSignupUrl() {
		String currentUrl = driver.getCurrentUrl();
		String invalidUrl = currentUrl.replaceFirst("://[^/]+", "://invalid.mosip.net");
		try {
			driver.get(invalidUrl);
		} catch (Exception e) {
			Assert.assertTrue(e.getMessage().contains("ERR_NAME_NOT_RESOLVED"));
		}
	}

	@When("user modifies the signup value in signup url")
	public void userModifiesSignupValue() {
		String currentUrl = driver.getCurrentUrl();
		int lastIndex = currentUrl.lastIndexOf("/signup");
		String modifiedUrl = currentUrl.substring(0, lastIndex) + "/invalid"
				+ currentUrl.substring(lastIndex + "/signup".length());
		driver.get(modifiedUrl);
	}

	@Then("verify error screen along with reset password button and register button is displayed")
	public void userVerifyErrorScreen() {
		Assert.assertTrue(invalidUrlPage.isPageNotExistErrorScreenDisplayed(), "Error screen did not displayed");
		Assert.assertTrue(invalidUrlPage.isResetPasswordButtonVisible(), "Reset password button did not displayed");
		Assert.assertTrue(invalidUrlPage.isRegisterButtonvisible(), "Register button did not displayed");
	}

	@When("user remove the signup value in signup url")
	public void userRemoveSignupValue() {
		String currentUrl = driver.getCurrentUrl();
		int lastIndex = currentUrl.lastIndexOf("/signup");
		String modifiedUrl = currentUrl.substring(0, lastIndex) + currentUrl.substring(lastIndex + "/signup".length());
		driver.get(modifiedUrl);
	}

	@Then("user click on reset password button")
	public void userClickOnResetPasswordButton() {
		invalidUrlPage.clickOnResetPasswordButton();
	}

	@When("user modifies the reset password value in signup url")
	public void userModifiesResetPasswordValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("reset-password", "invalid");
		driver.get(modifiedUrl);
	}

	@When("user remove the reset password value in signup url")
	public void userRemoveResetPasswordValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("reset-password", "");
		driver.get(modifiedUrl);
	}

	@When("user navigates to something went wrong page")
	public void userNavigatesToErrorPage() {
		String baseSignupUrl = EsignetConfigManager.getSignupUrl();
		String modifiedUrl = baseSignupUrl + "something-went-wrong";
		driver.get(modifiedUrl);
	}

	@Then("verify something went wrong our experts are working hard to make things working again error message displayed")
	public void userVerifySomethingWentWrongErrorScreen() {
		Assert.assertTrue(invalidUrlPage.isSomethingWentWrongErrorDisplayed(),
				"Something went wrong error screen did not displayed");
	}

	@When("user remove the something went wrong value in signup url")
	public void userRemoveSomethingWentWrongValue() {
		String currentUrl = driver.getCurrentUrl();
		String modifiedUrl = currentUrl.replace("something-went-wrong", "");
		driver.get(modifiedUrl);
	}

}