apiVersion: v2
name: oidc-ui
description: A Helm chart for MOSIP OIDC UI module
type: application
version: 1.1.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - oidc-ui
maintainers:
  - email: info@mosip.io
    name: MOSIP
