apiVersion: v2
name: apitestrig
description: A Helm chart to deploy APITESTRIG for MOSIP modules
type: application
version: 1.5.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - apitestrig
maintainers:
  - email: info@mosip.io
    name: MOSIP
