#---------------------------------- End point(s) relative URLs ----------------------------------#
actuatorEsignetEndpoint=/v1/esignet/actuator/env
actuatorSignupEndpoint=/v1/signup/actuator/env
csrfTokenEndpoint=/v1/esignet/csrf/token
tokenEndpoint=/v1/esignet/oauth/token
validateBindingEndpoint=ida-binding
esignetWellKnownEndPoint=/v1/esignet/oidc/.well-known/openid-configuration
keycloakAuthTokenEndPoint=/auth/realms/mosip/protocol/openid-connect/token
signupSettingsEndPoint=/v1/signup/settings
esignetActuatorPropertySection=classpath:/application-default.properties
# Allowed values for servicesNotDeployed is "sunbirdrc" for mosipid and mock plugin
servicesNotDeployed=sunbirdrc
sunBirdBaseURL=https://registry.released.mosip.net
eSignetbaseurl=https://esignet-qabase.esqa2.mosip.net
#------------------------- Need to check if these are used or not ------------------------#
OTPTimeOut = 181
attempt = 10
esignetSupportedLanguage=eng

# Mock identity system JSON schema (relative to public gateway base URL, same style as AddIdentity testscript)
mockIdentityIdentitySchemaEndpoint=/v1/mock-identity-system/identity/identity-schema


#---------------------------------- Modifiable Properties ----------------------------------------------------------#

#------------------------ Environment URLs and Database Connections ------------------------#

# Keycloak URL.
keycloak-external-url = https://iam.qa11new.mosip.net

# PostgreSQL URLs for audit and partner databases.
audit_url = jdbc:postgresql://qa11new.mosip.net:5433/mosip_audit
partner_url = jdbc:postgresql://qa11new.mosip.net:5433/mosip_ida

# Database server for connections.
db-server = api-internal.qa11new.mosip.net
db-port=5433

#------------------------ secrets and passwords  ------------------------#

#------------------------ Keycloak Passwords ------------------------#
# Used for Keycloak authentication.
keycloak_Password = 9gTMKIxJo6

#------------------------ PostgreSQL Database Passwords ------------------------#
# Credentials for connecting to Postgres databases.
audit_password = zN7%W$1Yudg&%21I
partner_password = zN7%W$1Yudg&%21I
postgres-password = zN7%W$1Yudg&%21I

#-------- Client Secret Keys ----------#
# These keys are used for various services, make sure to update the values as required when running locally.

mosip_partner_client_secret =
mosip_pms_client_secret = MeCaorB7539nVjn3
mosip_resident_client_secret = XqZR6sq0BDQgBHZ1
mosip_idrepo_client_secret = xqRlyKLZq9dQRnVD
mosip_reg_client_secret = bOHH5jkrVukFoH2K
mosip_admin_client_secret = LCPBKVoZWDSu5ThW
mosip_hotlist_client_secret = GJ6Z5U5ozv9qqtxC
mosip_regproc_client_secret = tdusNcErnfs1i6t3
mpartner_default_mobile_secret = 9Bdvdwj8tRMBvJCD
mosip_testrig_client_secret = YlpsOPiIsBCRfkA6
AuthClientSecret =
mosip_crvs1_client_secret =


#-------- Generic Configuration ----------#

# Enable or disable debugging mode (yes/no).
enableDebug = yes

# Whether to use pre-configured OTP (true/false).
usePreConfiguredOtp = true

# Mock Notification Channels (email/phone/email,phone).
mockNotificationChannel = email,phone


#------------------------ Mosip Components Base URLs ------------------------#
# Define base URLs for different components if required.
# Example:
# mosip_components_base_urls = auditmanager=api-internal.released.mosip.net;idrepository=api-internal.released.mosip.net;authmanager=api-internal.released.mosip.net;resident=api-internal.released.mosip.net;partnermanager=api-internal.released.mosip.net;idauthentication=api-internal.released.mosip.net;masterdata=api-internal.released.mosip.net;idgenerator=api-internal.released.mosip.net;policymanager=api-internal.released.mosip.net;preregistration=api-internal.released.mosip.net;keymanager=api-internal.released.mosip.net;mock-identity-system=api.released.mosip.net
# Feel free to add more components as needed.
mosip_components_base_urls =auditmanager=api-internal.qa11new.mosip.net;idrepository=api-internal.qa11new.mosip.net;authmanager=api-internal.qa11new.mosip.net;resident=api-internal.qa11new.mosip.net;partnermanager=pms-qabase.esqa2.mosip.net;idauthentication=api-internal.qa11new.mosip.net;masterdata=api-internal.qa11new.mosip.net;idgenerator=api-internal.qa11new.mosip.net;policymanager=pms-qabase.esqa2.mosip.net;preregistration=api-internal.qa11new.mosip.net;keymanager=api-internal.qa11new.mosip.net;
#------------------------ Module Name Pattern ------------------------#
# Define module name pattern if required.
# Example:
# moduleNamePattern = (mimoto|resident)
# Feel free to add more values as needed.
moduleNamePattern =


#------------------------ Uncomment for Local Run ------------------------#

# Path to the authentication certificates (if running locally, uncomment the below line and keep the value empty).
# authCertsPath =

# X-XSS-Protection: Controls the XSS (Cross-Site Scripting) filter in browsers.
# Values: (yes/no)
xssProtectionCheck = no

testCasesToExecute =

# Wait time (in milliseconds) after UIN generation in IDREPO before proceeding
uinGenerationProcessingDelayTimeInMilliSeconds = 90000

# Wait time (in milliseconds) after VID generation in Resident before proceeding
vidGenerationProcessingDelayTimeInMilliSeconds = 600000

# Maximum number of retry attempts for UIN availability check during OTP generation
uinGenMaxLoopCount = 20
#Uncomment below line for generate dependency JSON. This works only in case of local run using IDE.
#generateDependencyJson = yes