\c mosip_idp

GRANT CONNECT
   ON DATABASE mosip_idp
   TO idpuser;

GRANT USAGE
   ON SCHEMA idp
   TO idpuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA idp
   TO idpuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA idp
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO idpuser;

