package io.mosip.esignet.api.util;

public enum Action {
    OIDC_CLIENT_CREATE,
    OIDC_CLIENT_UPDATE,
    GET_OAUTH_DETAILS,
    TRANSACTION_STARTED,
    SEND_OTP,
    AUTHENTICATE,
    GET_AUTH_CODE,
    GENERATE_TOKEN,
    GET_USERINFO,
    DO_KYC_AUTH,
    DO_KYC_EXCHANGE
}
