// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteConsent = `-- name: DeleteConsent :exec
DELETE FROM consent_detail
WHERE client_id = $1 AND psu_token = $2
`

type DeleteConsentParams struct {
	ClientID string `db:"client_id" json:"client_id"`
	PsuToken string `db:"psu_token" json:"psu_token"`
}

func (q *Queries) DeleteConsent(ctx context.Context, arg DeleteConsentParams) error {
	_, err := q.db.ExecContext(ctx, deleteConsent, arg.ClientID, arg.PsuToken)
	return err
}

const getConsent = `-- name: GetConsent :one
SELECT id, client_id, psu_token, claims, authorization_scopes, cr_dtimes, expire_dtimes, signature, hash, accepted_claims, permitted_scopes FROM consent_detail
WHERE client_id = $1 AND psu_token = $2
LIMIT 1
`

type GetConsentParams struct {
	ClientID string `db:"client_id" json:"client_id"`
	PsuToken string `db:"psu_token" json:"psu_token"`
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) (ConsentDetail, error) {
	row := q.db.QueryRowContext(ctx, getConsent, arg.ClientID, arg.PsuToken)
	var i ConsentDetail
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PsuToken,
		&i.Claims,
		&i.AuthorizationScopes,
		&i.CrDtimes,
		&i.ExpireDtimes,
		&i.Signature,
		&i.Hash,
		&i.AcceptedClaims,
		&i.PermittedScopes,
	)
	return i, err
}

const insertConsentHistory = `-- name: InsertConsentHistory :exec
INSERT INTO consent_history (
	id,
	client_id,
	psu_token,
	claims,
	authorization_scopes,
	hash,
	accepted_claims,
	permitted_scopes,
	cr_dtimes,
	expire_dtimes
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertConsentHistoryParams struct {
	ID                  string         `db:"id" json:"id"`
	ClientID            string         `db:"client_id" json:"client_id"`
	PsuToken            string         `db:"psu_token" json:"psu_token"`
	Claims              string         `db:"claims" json:"claims"`
	AuthorizationScopes string         `db:"authorization_scopes" json:"authorization_scopes"`
	Hash                sql.NullString `db:"hash" json:"hash"`
	AcceptedClaims      sql.NullString `db:"accepted_claims" json:"accepted_claims"`
	PermittedScopes     sql.NullString `db:"permitted_scopes" json:"permitted_scopes"`
	CrDtimes            time.Time      `db:"cr_dtimes" json:"cr_dtimes"`
	ExpireDtimes        sql.NullTime   `db:"expire_dtimes" json:"expire_dtimes"`
}

func (q *Queries) InsertConsentHistory(ctx context.Context, arg InsertConsentHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertConsentHistory,
		arg.ID,
		arg.ClientID,
		arg.PsuToken,
		arg.Claims,
		arg.AuthorizationScopes,
		arg.Hash,
		arg.AcceptedClaims,
		arg.PermittedScopes,
		arg.CrDtimes,
		arg.ExpireDtimes,
	)
	return err
}

const upsertConsent = `-- name: UpsertConsent :exec
INSERT INTO consent_detail (
	id,
	client_id,
	psu_token,
	claims,
	authorization_scopes,
	hash,
	accepted_claims,
	permitted_scopes,
	cr_dtimes,
	expire_dtimes
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (client_id, psu_token) DO UPDATE SET
	claims               = EXCLUDED.claims,
	authorization_scopes = EXCLUDED.authorization_scopes,
	hash                 = EXCLUDED.hash,
	accepted_claims      = EXCLUDED.accepted_claims,
	permitted_scopes     = EXCLUDED.permitted_scopes,
	cr_dtimes            = EXCLUDED.cr_dtimes,
	expire_dtimes        = EXCLUDED.expire_dtimes
`

type UpsertConsentParams struct {
	ID                  string         `db:"id" json:"id"`
	ClientID            string         `db:"client_id" json:"client_id"`
	PsuToken            string         `db:"psu_token" json:"psu_token"`
	Claims              string         `db:"claims" json:"claims"`
	AuthorizationScopes string         `db:"authorization_scopes" json:"authorization_scopes"`
	Hash                sql.NullString `db:"hash" json:"hash"`
	AcceptedClaims      sql.NullString `db:"accepted_claims" json:"accepted_claims"`
	PermittedScopes     sql.NullString `db:"permitted_scopes" json:"permitted_scopes"`
	CrDtimes            time.Time      `db:"cr_dtimes" json:"cr_dtimes"`
	ExpireDtimes        sql.NullTime   `db:"expire_dtimes" json:"expire_dtimes"`
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) error {
	_, err := q.db.ExecContext(ctx, upsertConsent,
		arg.ID,
		arg.ClientID,
		arg.PsuToken,
		arg.Claims,
		arg.AuthorizationScopes,
		arg.Hash,
		arg.AcceptedClaims,
		arg.PermittedScopes,
		arg.CrDtimes,
		arg.ExpireDtimes,
	)
	return err
}
