package io.mosip.idp.core.util;

public enum Action {

    OIDC_CLIENT_CREATED,
    OIDC_CLIENT_UPDATED,
    OIDC_CLIENT_CREATE_FAILED,
    OIDC_CLIENT_UPDATE_FAILED,
    GET_OAUTH_DETAILS,
    TRANSACTION_STARTED,
    SEND_OTP_SUCCESS,
    SEND_OTP_FAILED,
    AUTHENTICATE,
    AUTHENTICATE_FAILED,
    AUTH_CODE_CREATED,
    AUTH_CODE_FAILED,
    GENERATE_TOKEN_SUCCESS,
    GENERATE_TOKEN_FAILED,
    USERINFO_SUCCESS,
    USERINFO_FAILED,
    KYC_AUTH_SUCCESS,
    KYC_AUTH_FAILED,
    KYC_EXCHANGE_SUCCESS,
    KYC_EXCHANGE_FAILED
}
