// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type ClientDetail struct {
	ID                string         `db:"id"                   json:"id"`
	Name              string         `db:"name"                 json:"name"`
	RpID              string         `db:"rp_id"                json:"rp_id"`
	LogoURI           string         `db:"logo_uri"             json:"logo_uri"`
	RedirectUris      string         `db:"redirect_uris"        json:"redirect_uris"`
	Claims            string         `db:"claims"               json:"claims"`
	AcrValues         string         `db:"acr_values"           json:"acr_values"`
	PublicKey         string         `db:"public_key"           json:"public_key"`
	PublicKeyHash     string         `db:"public_key_hash"      json:"public_key_hash"`
	EncPublicKey      sql.NullString `db:"enc_public_key"       json:"enc_public_key"`
	EncPublicKeyHash  sql.NullString `db:"enc_public_key_hash"  json:"enc_public_key_hash"`
	EncPublicKeyCert  sql.NullString `db:"enc_public_key_cert"  json:"enc_public_key_cert"`
	GrantTypes        string         `db:"grant_types"          json:"grant_types"`
	AuthMethods       string         `db:"auth_methods"         json:"auth_methods"`
	Status            string         `db:"status"               json:"status"`
	AdditionalConfig  sql.NullString `db:"additional_config"    json:"additional_config"`
	CrDtimes          time.Time      `db:"cr_dtimes"            json:"cr_dtimes"`
	UpdDtimes         sql.NullTime   `db:"upd_dtimes"           json:"upd_dtimes"`
}
