// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import "context"

// Querier is the interface satisfied by *Queries.
// Embed or accept this interface in code that needs to be testable without a
// real database connection.
type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (ClientDetail, error)
	GetClient(ctx context.Context, id string) (ClientDetail, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (ClientDetail, error)
}

var _ Querier = (*Queries)(nil) // compile-time interface check
