// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (ClientDetail, error)
	GetClient(ctx context.Context, id string) (ClientDetail, error)
	PatchClient(ctx context.Context, arg PatchClientParams) (ClientDetail, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (ClientDetail, error)
}

var _ Querier = (*Queries)(nil)
