/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (ClientDetail, error)
	GetClient(ctx context.Context, id string) (ClientDetail, error)
	PatchClient(ctx context.Context, arg PatchClientParams) (ClientDetail, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (ClientDetail, error)
}

var _ Querier = (*Queries)(nil)
