// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createClient = `-- name: CreateClient :one
INSERT INTO client_detail (
	id,
	name,
	rp_id,
	logo_uri,
	redirect_uris,
	claims,
	acr_values,
	public_key,
	public_key_hash,
	enc_public_key,
	enc_public_key_hash,
	enc_public_key_cert,
	grant_types,
	auth_methods,
	status,
	additional_config,
	cr_dtimes
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, name, rp_id, logo_uri, redirect_uris, claims, acr_values, public_key, public_key_hash, enc_public_key, enc_public_key_hash, enc_public_key_cert, grant_types, auth_methods, status, additional_config, cr_dtimes, upd_dtimes
`

type CreateClientParams struct {
	ID               string         `db:"id" json:"id"`
	Name             string         `db:"name" json:"name"`
	RpID             string         `db:"rp_id" json:"rp_id"`
	LogoUri          string         `db:"logo_uri" json:"logo_uri"`
	RedirectUris     string         `db:"redirect_uris" json:"redirect_uris"`
	Claims           string         `db:"claims" json:"claims"`
	AcrValues        string         `db:"acr_values" json:"acr_values"`
	PublicKey        string         `db:"public_key" json:"public_key"`
	PublicKeyHash    string         `db:"public_key_hash" json:"public_key_hash"`
	EncPublicKey     sql.NullString `db:"enc_public_key" json:"enc_public_key"`
	EncPublicKeyHash sql.NullString `db:"enc_public_key_hash" json:"enc_public_key_hash"`
	EncPublicKeyCert sql.NullString `db:"enc_public_key_cert" json:"enc_public_key_cert"`
	GrantTypes       string         `db:"grant_types" json:"grant_types"`
	AuthMethods      string         `db:"auth_methods" json:"auth_methods"`
	Status           string         `db:"status" json:"status"`
	AdditionalConfig sql.NullString `db:"additional_config" json:"additional_config"`
	CrDtimes         time.Time      `db:"cr_dtimes" json:"cr_dtimes"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (ClientDetail, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.RpID,
		arg.LogoUri,
		arg.RedirectUris,
		arg.Claims,
		arg.AcrValues,
		arg.PublicKey,
		arg.PublicKeyHash,
		arg.EncPublicKey,
		arg.EncPublicKeyHash,
		arg.EncPublicKeyCert,
		arg.GrantTypes,
		arg.AuthMethods,
		arg.Status,
		arg.AdditionalConfig,
		arg.CrDtimes,
	)
	var i ClientDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RpID,
		&i.LogoUri,
		&i.RedirectUris,
		&i.Claims,
		&i.AcrValues,
		&i.PublicKey,
		&i.PublicKeyHash,
		&i.EncPublicKey,
		&i.EncPublicKeyHash,
		&i.EncPublicKeyCert,
		&i.GrantTypes,
		&i.AuthMethods,
		&i.Status,
		&i.AdditionalConfig,
		&i.CrDtimes,
		&i.UpdDtimes,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, name, rp_id, logo_uri, redirect_uris, claims, acr_values, public_key, public_key_hash, enc_public_key, enc_public_key_hash, enc_public_key_cert, grant_types, auth_methods, status, additional_config, cr_dtimes, upd_dtimes FROM client_detail
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id string) (ClientDetail, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i ClientDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RpID,
		&i.LogoUri,
		&i.RedirectUris,
		&i.Claims,
		&i.AcrValues,
		&i.PublicKey,
		&i.PublicKeyHash,
		&i.EncPublicKey,
		&i.EncPublicKeyHash,
		&i.EncPublicKeyCert,
		&i.GrantTypes,
		&i.AuthMethods,
		&i.Status,
		&i.AdditionalConfig,
		&i.CrDtimes,
		&i.UpdDtimes,
	)
	return i, err
}

const patchClient = `-- name: PatchClient :one
UPDATE client_detail SET
	name                = $2,
	logo_uri            = $3,
	redirect_uris       = $4,
	claims              = $5,
	acr_values          = $6,
	grant_types         = $7,
	auth_methods        = $8,
	status              = $9,
	additional_config   = $10,
	enc_public_key      = $11,
	enc_public_key_hash = $12,
	enc_public_key_cert = $13,
	upd_dtimes          = $14
WHERE id = $1
  AND upd_dtimes IS NOT DISTINCT FROM $15
RETURNING id, name, rp_id, logo_uri, redirect_uris, claims, acr_values, public_key, public_key_hash, enc_public_key, enc_public_key_hash, enc_public_key_cert, grant_types, auth_methods, status, additional_config, cr_dtimes, upd_dtimes
`

type PatchClientParams struct {
	ID                string         `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	LogoUri           string         `db:"logo_uri" json:"logo_uri"`
	RedirectUris      string         `db:"redirect_uris" json:"redirect_uris"`
	Claims            string         `db:"claims" json:"claims"`
	AcrValues         string         `db:"acr_values" json:"acr_values"`
	GrantTypes        string         `db:"grant_types" json:"grant_types"`
	AuthMethods       string         `db:"auth_methods" json:"auth_methods"`
	Status            string         `db:"status" json:"status"`
	AdditionalConfig  sql.NullString `db:"additional_config" json:"additional_config"`
	EncPublicKey      sql.NullString `db:"enc_public_key" json:"enc_public_key"`
	EncPublicKeyHash  sql.NullString `db:"enc_public_key_hash" json:"enc_public_key_hash"`
	EncPublicKeyCert  sql.NullString `db:"enc_public_key_cert" json:"enc_public_key_cert"`
	UpdDtimes         sql.NullTime   `db:"upd_dtimes" json:"upd_dtimes"`
	ExpectedUpdDtimes sql.NullTime   `db:"expected_upd_dtimes" json:"expected_upd_dtimes"`
}

func (q *Queries) PatchClient(ctx context.Context, arg PatchClientParams) (ClientDetail, error) {
	row := q.db.QueryRowContext(ctx, patchClient,
		arg.ID,
		arg.Name,
		arg.LogoUri,
		arg.RedirectUris,
		arg.Claims,
		arg.AcrValues,
		arg.GrantTypes,
		arg.AuthMethods,
		arg.Status,
		arg.AdditionalConfig,
		arg.EncPublicKey,
		arg.EncPublicKeyHash,
		arg.EncPublicKeyCert,
		arg.UpdDtimes,
		arg.ExpectedUpdDtimes,
	)
	var i ClientDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RpID,
		&i.LogoUri,
		&i.RedirectUris,
		&i.Claims,
		&i.AcrValues,
		&i.PublicKey,
		&i.PublicKeyHash,
		&i.EncPublicKey,
		&i.EncPublicKeyHash,
		&i.EncPublicKeyCert,
		&i.GrantTypes,
		&i.AuthMethods,
		&i.Status,
		&i.AdditionalConfig,
		&i.CrDtimes,
		&i.UpdDtimes,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE client_detail SET
	name                = $2,
	logo_uri            = $3,
	redirect_uris       = $4,
	claims              = $5,
	acr_values          = $6,
	grant_types         = $7,
	auth_methods        = $8,
	status              = $9,
	additional_config   = $10,
	upd_dtimes          = $11
WHERE id = $1
RETURNING id, name, rp_id, logo_uri, redirect_uris, claims, acr_values, public_key, public_key_hash, enc_public_key, enc_public_key_hash, enc_public_key_cert, grant_types, auth_methods, status, additional_config, cr_dtimes, upd_dtimes
`

type UpdateClientParams struct {
	ID               string         `db:"id" json:"id"`
	Name             string         `db:"name" json:"name"`
	LogoUri          string         `db:"logo_uri" json:"logo_uri"`
	RedirectUris     string         `db:"redirect_uris" json:"redirect_uris"`
	Claims           string         `db:"claims" json:"claims"`
	AcrValues        string         `db:"acr_values" json:"acr_values"`
	GrantTypes       string         `db:"grant_types" json:"grant_types"`
	AuthMethods      string         `db:"auth_methods" json:"auth_methods"`
	Status           string         `db:"status" json:"status"`
	AdditionalConfig sql.NullString `db:"additional_config" json:"additional_config"`
	UpdDtimes        sql.NullTime   `db:"upd_dtimes" json:"upd_dtimes"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (ClientDetail, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.LogoUri,
		arg.RedirectUris,
		arg.Claims,
		arg.AcrValues,
		arg.GrantTypes,
		arg.AuthMethods,
		arg.Status,
		arg.AdditionalConfig,
		arg.UpdDtimes,
	)
	var i ClientDetail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RpID,
		&i.LogoUri,
		&i.RedirectUris,
		&i.Claims,
		&i.AcrValues,
		&i.PublicKey,
		&i.PublicKeyHash,
		&i.EncPublicKey,
		&i.EncPublicKeyHash,
		&i.EncPublicKeyCert,
		&i.GrantTypes,
		&i.AuthMethods,
		&i.Status,
		&i.AdditionalConfig,
		&i.CrDtimes,
		&i.UpdDtimes,
	)
	return i, err
}
