{{- if and .Values.reports.persistence.enabled (not .Values.reports.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apitestrig.reportsClaimName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.reports.persistence.storageClass }}
  {{- if eq "-" .Values.reports.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.reports.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  accessModes:
    {{- range .Values.reports.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.reports.persistence.size | quote }}
{{- end }}
