{{- if and .Values.apitestrig.conformancePlanConfig.enabled (not .Values.apitestrig.conformancePlanConfig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apitestrig.conformancePlanConfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $filename, $content := .Values.apitestrig.conformancePlanConfig.files }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
