package utils;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import models.Uin;

public class UINManager {

	private static final BlockingQueue<Uin> availableUINs = new LinkedBlockingQueue<>();

	static {
		String uins = EsignetConfigManager.getproperty("uin");

		if (uins != null && !uins.isEmpty()) {
			String[] uinList = uins.split(",");

			for (String uin : uinList) {
				availableUINs.add(new Uin(uin));
			}
		} else {

			int totalUINs = 3;
			for (int i = 1; i <= totalUINs; i++) {
				String prefix = "AddIdentity_withValidParameters_smoke_UIN" + i + "_Pos_";
				String uin = autoGeneratedIDValueCache.get(prefix + "UIN");
				if (uin != null && !uin.isEmpty()) {
					availableUINs.add(new Uin(uin));
				}
			}
			if (availableUINs.isEmpty()) {
				throw new IllegalStateException("No UINs available in config ");
			}
		}
	}

	public static Uin acquireUIN() throws InterruptedException {
		return availableUINs.take();
	}

	public static void releaseUIN(Uin uin) {
		availableUINs.offer(uin);
	}

	public static Uin acquireUINWithTimeout(long timeoutSeconds) throws InterruptedException {
		return availableUINs.poll(timeoutSeconds, TimeUnit.SECONDS);
	}
}
