package utils;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import models.Uin;

public class UINManager {

	private static final BlockingQueue<Uin> availableUINs = new LinkedBlockingQueue<>();

	static {
		String uins = EsignetConfigManager.getproperty("uin");

		if (!uins.isEmpty() || !uins.equals(null)) {
			String[] uinList = uins.split(",");

			for (String uin : uinList) {
				availableUINs.add(new Uin(uin));
			}
		} else {

			int totalUINs = 3;
			for (int i = 1; i <= totalUINs; i++) {
				String prefix = "AddIdentity_withValidParameters_smoke_UIN" + i + "_Pos_";
				availableUINs.add(new Uin(autoGeneratedIDValueCache.get(prefix + "UIN")));
			}

		}
	}

	public static Uin acquireUIN() throws InterruptedException {
		return availableUINs.take();
	}

	public static void releaseUIN(Uin uin) {
		availableUINs.offer(uin);
	}

	public static Uin acquireUINWithTimeout(long timeoutSeconds) throws InterruptedException {
		return availableUINs.poll(timeoutSeconds, TimeUnit.SECONDS);
	}
}
