package utils;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;

import java.util.concurrent.LinkedBlockingQueue;

import java.util.concurrent.TimeUnit;

import models.Vid;

public class VIDManager {

	private static final BlockingQueue<Vid> availableVIDs = new LinkedBlockingQueue<>();

	private static volatile boolean initialized;

	private VIDManager() {

	}

	private static synchronized void ensureInitialized() {

		if (initialized) {

			return;

		}

		String vid = EsignetConfigManager.getproperty("vid");

		if (vid != null && !vid.isEmpty()) {

			for (String entry : vid.split(",")) {

				if (!entry.trim().isEmpty()) {

					availableVIDs.add(new Vid(entry.trim()));

				}

			}

		} else {

			String perpetualVid = autoGeneratedIDValueCache.get(EsignetUtil.PERPETUAL_VID_CACHE_KEY);

			String temporaryVid = autoGeneratedIDValueCache.get(EsignetUtil.TEMPORARY_VID_CACHE_KEY);

			if (perpetualVid != null && !perpetualVid.isEmpty()) {

				availableVIDs.add(new Vid(perpetualVid));

			}

			if (temporaryVid != null && !temporaryVid.isEmpty()) {

				availableVIDs.add(new Vid(temporaryVid));

			}

		}

		initialized = true;

	}

	public static boolean hasAvailableVid() {

		ensureInitialized();

		return !availableVIDs.isEmpty();

	}

	public static Vid acquireVID() throws InterruptedException {

		ensureInitialized();

		if (availableVIDs.isEmpty()) {

			throw new IllegalStateException("No VID available in config or generated from prerequisite CreateVID");

		}

		return availableVIDs.take();

	}

	public static void releaseVID(Vid vid) {

		availableVIDs.offer(vid);

	}

	public static Vid acquireVIDWithTimeout(long timeoutSeconds) throws InterruptedException {

		ensureInitialized();

		return availableVIDs.poll(timeoutSeconds, TimeUnit.SECONDS);

	}

}

