package utils;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import models.Vid;

public class VIDManager {

	private static final BlockingQueue<Vid> availableVIDs = new LinkedBlockingQueue<>();

	static {
		String vid = EsignetConfigManager.getproperty("vid");

		if (vid != null && !vid.isEmpty()) {
			String[] vidList = vid.split(",");

			for (String v : vidList) {
				availableVIDs.add(new Vid(v.trim()));
			}

		} else {
			String prefix = "Generate_Perpetual_VID_Valid_Smoke_sid";
			String generatedVID = autoGeneratedIDValueCache.get(prefix + "_vid");

			if (generatedVID != null && !generatedVID.isEmpty()) {
				availableVIDs.add(new Vid(generatedVID));
			} else {
				throw new IllegalStateException("No VID available in config or generated from TC");
			}
		}
	}

	public static Vid acquireVID() throws InterruptedException {
		return availableVIDs.take();
	}

	public static void releaseVID(Vid vid) {
		availableVIDs.offer(vid);
	}

	public static Vid acquireVIDWithTimeout(long timeoutSeconds) throws InterruptedException {
		return availableVIDs.poll(timeoutSeconds, TimeUnit.SECONDS);
	}
}