package utils;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import models.Vid;

public class VIDManager {

	private static final BlockingQueue<Vid> availableVIDs = new LinkedBlockingQueue<>();

	static {
		String vid = EsignetConfigManager.getproperty("vid");

		if (vid != null && !vid.isEmpty()) {
			String[] vidList = vid.split(",");

			for (String v : vidList) {
				availableVIDs.add(new Vid(v.trim()));
			}

		} else {
			String perpetualVid = autoGeneratedIDValueCache.get("Generate_Perpetual_VID_Valid_Smoke_sid_vid");
			String temporaryVid = autoGeneratedIDValueCache.get("Generate_Temporary_VID_Valid_Smoke_sid_vid");

			if (perpetualVid != null && !perpetualVid.isEmpty()) {
				availableVIDs.add(new Vid(perpetualVid));
			}
			if (temporaryVid != null && !temporaryVid.isEmpty()) {
				availableVIDs.add(new Vid(temporaryVid));
			}
			if (availableVIDs.isEmpty()) {
				throw new IllegalStateException("No VID available in config or generated from TC");
			}
		}
	}

	public static Vid acquireVID() throws InterruptedException {
		return availableVIDs.take();
	}

	public static void releaseVID(Vid vid) {
		availableVIDs.offer(vid);
	}

	public static Vid acquireVIDWithTimeout(long timeoutSeconds) throws InterruptedException {
		return availableVIDs.poll(timeoutSeconds, TimeUnit.SECONDS);
	}
}