apiVersion: v2
name: idp-binding
description: A Helm chart for MOSIP idp-binding-service module
type: application
version: 0.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - idp-binding-service
maintainers:
  - email: info@mosip.io
    name: MOSIP
