{{- if .Values.uitestrig.browserstack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uitestrig.browserstackSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  browserstack_username: {{ required "uitestrig.browserstack.username is required when uitestrig.browserstack.enabled" .Values.uitestrig.browserstack.username | quote }}
  browserstack_access_key: {{ required "uitestrig.browserstack.accessKey is required when uitestrig.browserstack.enabled" .Values.uitestrig.browserstack.accessKey | quote }}
{{- end }}
