services:
  database:
    image: 'postgres:bookworm'
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    restart: always

  mock-identity-system:
    image: 'mosipdev/mock-identity-system:develop'
    user: root
    ports:
      - 8082:8082
    environment:
      - container_user=mosip
      - active_profile_env=default,local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mosip_mockidentitysystem?currentSchema=mockidentitysystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MOSIP_ESIGNET_HOST=localhost:8080
    depends_on:
      - database

  mock-relying-party-service:
    image: 'mosipdev/mock-relying-party-service:develop'
    user: root
    ports:
      - 8888:8888
    environment:
      - ESIGNET_SERVICE_URL=http://host.docker.internal:8080
      - ESIGNET_AUD_URL=http://localhost:8080
      - ESIGNET_PAR_ENDPOINT=http://host.docker.internal:8080/oauth2/par
      - ESIGNET_PAR_AUD_URL=http://localhost:8080
      - TOKEN_ENDPOINT=/oauth2/token
      - USERINFO_ENDPOINT=/oauth2/userinfo
      - CLIENT_PRIVATE_KEY=eyJrdHkiOiJSU0EiLCJuIjoicmw0dHMyckdoNWF3ckZPemdzU1FSdXh5V002eUItMUhxeFJsMFhMclBtaWRrU0tCaXNrNnRBYXBUZkcyajNsbVozNXNIU0U5bXk4YjJoR2U0QUl5bWZpei1QUkliLTMyYVVrbjlOdUJCUUVpUENGRmh6ZGdWR0Vnb1Zkd1pRS19OZFc5TEFRLUc0S29nZkw0UGZ3NjJ4ZzlIQlAzTFVmMjUyRkY1dktQYnNmWEItdXRmN3gwUi00LTBmUmxWWmVGeC1WRWt3Zi1ZRnlQWHdRMFJjNEZLOHJsWUNiT2Y5NjhiMl9ubzNUUFRpNDFkRmV5X1lqZTQ1VkhqUnpFbnZ1WkpPN0RPTTdONy1QbE45cVJEeFFNck1RdElMUWN3c1Z3YmxWbFdpZ2lPdWpVS3dXSjVfZ2htaFlQWUozMVJPWVJkaXZudGhTb3JSX1Q0WmR5alFtWXF3IiwiZSI6IkFRQUIiLCJkIjoiREMxWWtnbnRhOFVBSV9ERDB4TS1JNE12YUhpbGpKSFdGUGV3M19rMHZqV0R6TmNma1RLRXc5Tno3eFVTZmtvOTlydjktZVRRanNOY29HbmxuSzJhbkxwMmV5R05qaW8zVzFxaXR6ZG9keEhXc3czOGN6a2wtWTZVNlotWHpQNFlTTDZ3czRwbnBLS0hJOExLUjYzb2xhb2MyUmFqTVo3YWVvWGJ0MTY0MmZBWTRiRXo0OWtHMlVfSmdXam5pclZPOGZzZGxtTnlfNTEtaVhkLTNnNzVGZlBRWDhNVFl5OHdmbk13d25lNlhIT3J0bWt3MHRReE5sVkx3LXlDNkM2TlBNVWxJc1p4ODQxZlNKaGdnVS0ycmhSYmdmdlQwZG15OF8xUHlIc2VEbVdLSFFleHRYM2tYTkV3RDZVcjJCaUQxTmU5RkZJSnd5VW1pcUNidTE4cjlRIiwicCI6IjU5SEExYXB0RElEdUgydVlLMTFYbkF2S1lQMDhWdTI3UUExeUF0N21MT3czQjFfOVVxVHIzeFhuLXNaRHZoY19BRXpDRHc4QUhGTjV1YTVzdUtUR0dqckVlbXJzd19qLVNEWktpUWlTVmhvVHFnZTZLQ3RaZVR0U09LbFdRcUJqNGQtS2ctc1QtWnJ4RDh4YXpQYU5YY1NOYlBZWG9PLXpkY1VVMWRlNFhYOCIsInEiOiJ3STVPR3RSeXByX1FqNlhxWGM3R0ZKbnFyZlFpb05XcnR0LUFYbUVOQTVlS0NyY3IwTHJORWtQREtvZ1d4MURlQnRpY2YyOFBYelJORVp3Y1pBMlhwVVJ3ajYxSm9tbVAyUV93SHNDRENaVEVLd0JUX2ZOUjdobDJ1bC1jQWM1dUQwUERYRWlPQnJhd1R2Zk5ZNmZVZGE0eG9KRTRtc0I2QVVyT1JVUWZNdFUiLCJkcCI6ImpGbWp4RGpBZVBkLU02dXluMTZOOGozNU15dGVZc3JmdVhIcWV1NTBzUEg2aHc2SWtvYWlfNWVGc1lCajl5eWZ5aEN1MU9zaUNBUktDQzhnUjlJSzFrcUtOZ3VTZVR2QXhfdUd1TnhsckpkeEhGbzlUS0NpTlJIRFAtYldBTlNXWkdRd3VwbVNxR1kwV0hwQzV5REdpZVM4TXlIelFFNmZla2Z0eTJJbGp3VSIsImRxIjoia3JjYkhlaEgzM1FCcHFJbG5BcGo5T2g5M3NOSTYwRkRFQmpseDRPdEZkS09OTEh5YVowYmlkSWx6NjlYbzlDakM1WmFULUxBVktzV0dkZlg3Z2hKUm55S1EzOG12dUF0NFpiNlA0UXhrOGhOV19KcERQTXJ0djZoNzBuUUpiUXpPZUJJNTNURS1xcVNWZWtNRHVXZXhYZlBpbWQ4T0xWMWdLeU4xRXNlZG0wIiwicWkiOiJ1eXVqaGhnUG5ndzlTNFpPOUdoYkJsZ2hWN19hSEZzYm5sbGVMZ3k4eU1iNm5VbENiS1RjZlNmQ3E4Z0J1cktFaDU0eGpBT2hjMERrX2FsaVNVUTJUY3BUaGpubVVzTVpwVlp5d3pkUmRJbFBjOTNLX2ZVVHlfdkdXcWstcWNGTkhQamNJX2JvRGtCdzBCNEE2VmlfTDE5TWN2QVV2QlBlOTZOWGF3QmtqZEEiLCJraWQiOiJUTGEwQVFpUDM5MHY0QVdDbEVUSHBPYVVQczVDUEVEcUNVQS0zakw3M05nIiwidXNlIjoic2lnIn0=
      - JWE_USERINFO_PRIVATE_KEY=ewogICAgInAiOiAieF8zWXBZejI2aE1ZNVRleUhtRmVDeHFGMEotTzRIWnd4b0hsV3VkZlVDYV9vQktfeXJhQWxJOWtQYUF0Y1d1cV83S2V5SzFnS2FRQ005LWVUYnE4cnRGc3ZSRU15OW9ORk5scnlxMmVjTjVWSTBxMGMzM2gyd1NzM3FwWDBuVXNMMC13TTIzaWcyWkkzUkE1NWpWUzdEV3laTkJLdFF6TS1wRUVfU2RRTldrIiwKICAgICJrdHkiOiAiUlNBIiwKICAgICJxIjogInZJdnJtZE9wMEZUX3cxSUg0M2tjdG1VeEJWRUdScVdKcy1DZ0tuU1hTaFRmam93c3AtZ09CalVoRE1yNC13b0dyZVZyMkRaeDVPeGNtbDJ4eExHekJKSzMxLWZxQTFyYWN6S3F2M3RBbnpPMnhoOVJUSGtnZDR0c01CMGFlalAtTFVEajM4eGxhSWtyQlZ2b0NlN1ZpS29iSW12YVZweUdlM1hidV9hSWoxMCIsCiAgICAiZCI6ICJVQ0dCUTZ2aUtjWTVTc3E0YzdiTFUwbUVBWjAteXdrT3AteXpkWGppNGZ0LXlRRXpKMVdtQWp1dTlmcWh4ZVBKdkpWekZQLWduY0NVZzc0dEpiY2F3Q0IzMVIxUHJycDhKY1VnYk9fcFJmT3lwWFI3Zm1yYkpyWjRMc0ZkZURyUzVBdUFJS0NOVy1RQTRZajQxcnFBSEw4OEtOQXRvR01IdGQ5VDZ5dkhZUUVpMmtSbUUxZHQ4OXhqRjRHR2E2MFBzaml3RVJvdm9EUWxjWmtwekM5QXpPRm80NXZ6a2RtSWlLRlFVR1hkRWJjSFhVOVRmWFdSc3RhOFlsdGRWVWM3NHhsbk13MDJtNm4tWjU3VG5kdVFOSFJHMVhZd3lGZEh3RFI5S0pDU0lCR3htRDRDWVNVdTc1b0JRLWdVZUtYQ1Y2UENiQVRoT1J4ZG9sako2SkhtNFEiLAogICAgImUiOiAiQVFBQiIsCiAgICAidXNlIjogInNpZyIsCiAgICAicWkiOiAiSDRWd2JHQkR3UFJkenJzZVpYSFo4M29kakwwNnJhWnEybzZaQ1FnMzdTUFVpVHY4dWZNMHNJaHJGdEhKd0xUN1ZXVlRIMy0xZ00xOEZvcVBHekVUNGhnN252UE1FaVpaQmVzUGJ6NWpQb2VLeTFHczFfSWVxWVRjbkxKRzM0azZfck1KVXFzeUZWQ001bjY5Ykcyaml5SzEzcjFRVVNWcGdYOFJqX1RrMGRNIiwKICAgICJkcCI6ICJyQzN4SW42ZGFlTXRNTkxscC1BLUhpTWtoX3VHXzlzWXR0N0lmcDNxWWxBcDlILVAzYy1JSGQ3aDkyaDdGMFlSXzNoaDJmWGliNWREU2pQQXo3endpelhFZjNZNVpSd0MzU3RlOFN6TzF1LWpydkczTUNOMW1xR0l6MThxb3dlOEZiTnV5S2hYTnJlT0RielZqRXZtYTNURGRLWWJXNHA4dzFDdFVlSlIzTmsiLAogICAgImFsZyI6ICJSUzI1NiIsCiAgICAiZHEiOiAiRklNOGZKM1VpYl9WbTVCZkgxWmIwMVFyQXlNUGhid1l3U01kQ2NGcGZEdk5IcHNOZUs3OFo1eDhIZ0l2R0ZDODdVcGFjMGxwRnJqSVVsc0RMaDBQRnQ1SGRndmJIOFpRb2R2UFM4bkNfQThLUVhfQ3Zva25DUnA0Q0x3QjEyMjBwNE81eHUxYjB3V3BVb252TXJWek1jMGY2cHpGUWtzQkxvbGlBSThQeUZrIiwKICAgICJuIjogImswdTVfR2RhTkRRbXNlS240UWgxYlhTblV1ODhvOHZpRFAza1NRTVJqRG9xaG9RYXpRRUItVWJxREI0UnhKS1A0Y2VFWnJLemVaQnl6U0hqN0pZU2Nxb0Q3b3V4RXY0X1FxMnQxREFuR21GYTUycGVjU29VclIxbFBvQmZGRE5LTndFSzJiS25TbEdsVXRhYnJudjNsRXBkck1EM2xOX1RYNlJrVjJXT0k5NF9PT09tU29mTEFuWVlkUGN0QmVGLW0tb0JOczBCcklSRUVqRkc3Y2dZYlpIVE55Y0lnNnJnVVVMVVNTeVE4blhFSFNRUy1DWUF6ek9HTlFvTUdGdmMyazNwLTgya1pZNHY2NXowX2s3RWVlZjU4UDI3TDhVY1plVEh5YUp3LUJjYjFXMThQNGJRakU1dVVybFEtUjBZNGdBeGE5d3dSaGtrQVFXUFc4RU9KUSIKfQ==
      - USERINFO_RESPONSE_TYPE=jwt
      - SCOPE_USER_PROFILE=openid profile
      - REDIRECT_URI=http://localhost:3000/userprofile
      - ACRS=mosip:idp:acr:linked-wallet mosip:idp:acr:knowledge mosip:idp:acr:generated-code mosip:idp:acr:password
      - CLAIMS_USER_PROFILE={"userinfo":{"name":{"essential":true},"phone_number":{"essential":true},"verified_claims":[{"verification":{"trust_framework":{"value":"ABC TF"}},"claims":{"phone_number":{"essential":true}}},{"verification":{"trust_framework":{"value":"XYZ TF"}},"claims":{"name":{"essential":true}}}]},"id_token":{}}

  mock-relying-party-ui:
    image: 'mosipdev/mock-relying-party-ui:develop'
    user: root
    ports:
      - 3000:3000
    depends_on:
      - mock-relying-party-service
    environment:
      - container_user=mosip
      - ESIGNET_UI_BASE_URL=http://localhost:8080
      - MOCK_RELYING_PARTY_SERVER_URL=http://localhost:8888
      - REDIRECT_URI=http://localhost:3000/userprofile
      - CLIENT_ID=I6eXdnnLGGj2A2BcTL-jug_0ujpnQXlBpKAbBCkGWEB
      - ACRS=mosip:idp:acr:static-code%20mosip:idp:acr:generated-code%20mosip:idp:acr:biometrics%20mosip:idp:acr:linked-wallet%20mosip:idp:acr:password%20mosip:idp:acr:knowledge
      - REDIRECT_URI_REGISTRATION=http://localhost:3000/registration
      - SIGN_IN_BUTTON_PLUGIN_URL=http://localhost:8080/plugins/sign-in-button-plugin.js
      - DISPLAY=page
      - GRANT_TYPE=authorization_code
      - CLAIMS_LOCALES=en
      - SCOPE_USER_PROFILE=openid profile
      - CLAIMS_USER_PROFILE=%7B%22userinfo%22%3A%7B%22birthdate%22%3A%7B%22essential%22%3Atrue%7D%2C%22verified_claims%22%3A%5B%7B%22verification%22%3A%7B%22trust_framework%22%3A%7B%22value%22%3A%22ABC%20TF%22%7D%2C%22verification_process%22%3Anull%7D%2C%22claims%22%3A%7B%22phone_number%22%3A%7B%22essential%22%3Atrue%7D%7D%7D%2C%7B%22verification%22%3A%7B%22trust_framework%22%3A%7B%22value%22%3A%22XYZ%20TF%22%7D%7D%2C%22claims%22%3A%7B%22name%22%3A%7B%22essential%22%3Atrue%7D%7D%7D%5D%7D%2C%22id_token%22%3A%7B%7D%7D
      - CLAIMS_REGISTRATION=%7B%22userinfo%22:%7B%22given_name%22:%7B%22essential%22:true%7D,%22phone_number%22:%7B%22essential%22:false%7D,%22email%22:%7B%22essential%22:true%7D,%22picture%22:%7B%22essential%22:false%7D,%22gender%22:%7B%22essential%22:false%7D,%22birthdate%22:%7B%22essential%22:false%7D,%22address%22:%7B%22essential%22:false%7D%7D,%22id_token%22:%7B%7D%7D
      - DEFAULT_LANG=en
      - FALLBACK_LANG=%7B%22label%22%3A%22English%22%2C%22value%22%3A%22en%22%7D
      - PAR_CALLBACK_NAME=get_requestUri1
      - PAR_CALLBACK_TIMEOUT=5000
      - DPOP_CALLBACK_NAME=get_dpop_jkt1
      - CODE_CHALLENGE=get_code_challenge
      - AUTHORIZE_ENDPOINT=/oauth2/authorize
    volumes:
      - ./rp-nginx.conf:/etc/nginx/nginx.conf 