// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template.sql

package sqlc

import (
	"context"
)

const example = `-- name: Example :one
SELECT 1
`

func (q *Queries) Example(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, example)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
