domainConfig:
  INSTALLATION_DOMAIN: sandbox.xyz.net
  MOSIP_VERSION: develop
  MOSIP_API_HOST: api.sandbox.xyz.net
  MOSIP_IAM_EXTERNAL_HOST: iam.sandbox.xyz.net
  MOSIP_API_INTERNAL_HOST: api-internal.sandbox.xyz.net
  MOSIP_KAFKA_HOST: kafka.sandbox.xyz.net
  MOSIP_ESIGNET_HOST: esignet.sandbox.xyz.net
  MOSIP_POSTGRES_HOST: esignet-postgres.sandbox.xyz.net
  MOSIP_SIGNUP_HOST: signup.sandbox.xyz.net
  MOSIP_SMTP_HOST: smtp.sandbox.xyz.net
