dbUserPasswords:
  dbuserPassword: ""

databases:
  mosip_esignet:
    enabled: true
    scriptsDir: mosip_esignet      # fixed - must match db_scripts/ folder in repo
    dbName: mosip_esignet          # customize e.g. mosip_esignet02
    dbUser: esignetuser            # customize e.g. esignetuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet.git
    branch: develop
