apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-ui
spec:
  hosts:
  - "*"
  gateways:
    - kafka-ui
  http:
  - route:
    - destination:
        host: {{ .Values.installName }}
        port:
          number: 80
    headers:
      request:
        set:
          x-forwarded-proto: https

