apiVersion: v2
name: esignet-apitestrig
description: A Helm chart to deploy the Go-based eSignet API test rig (api-test)
type: application
version: 0.0.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - esignet
  - apitestrig
maintainers:
  - email: info@mosip.io
    name: MOSIP
