package runners;

import java.util.List;
import java.util.Map;

import org.testng.TestNG;

import constants.ESignetConstants;
import io.mosip.testrig.apirig.testrunner.BaseTestCase;
import io.mosip.testrig.apirig.testrunner.ExtractResource;
import io.mosip.testrig.apirig.utils.AdminTestUtil;
import utils.EsignetConfigManager;
import utils.EsignetUtil;

public class GenerateVidRunner {

	public static String jarUrl = GenerateVidRunner.class.getProtectionDomain().getCodeSource().getLocation()
			.getPath();

	public static void main(String[] args) {
		String runType = getRunType();

		BaseTestCase.setRunContext(runType, jarUrl);
		ExtractResource.removeOldMosipTestTestResource();
		if (runType.equalsIgnoreCase("JAR")) {
			ExtractResource.extractCommonResourceFromJar();
		} else {
			ExtractResource.copyCommonResources();
		}

		AdminTestUtil.init();
		EsignetConfigManager.init();
		EsignetUtil.getPluginName();

		BaseTestCase.initialize();
		BaseTestCase.currentModule = ESignetConstants.ESIGNETUI_MODULENAME;
		BaseTestCase.certsForModule = ESignetConstants.ESIGNETUI_MODULENAME;
		AdminTestUtil.copymoduleSpecificAndConfigFile(ESignetConstants.ESIGNETUI_MODULENAME);
		AdminTestUtil.getRequiredField();

		TestNG runner = new TestNG();
		runner.setTestSuites(List.of("testNgXmlFiles/GenerateVidSuite.xml"));
		runner.setOutputDirectory("testng-report");
		runner.run();

		System.out.println("\n===== Generated auto IDs (includes UIN and VID) =====");
		for (Map.Entry<String, String> entry : AdminTestUtil.autoGeneratedIDValueCache.entrySet()) {
			System.out.println(entry.getKey() + " = " + entry.getValue());
		}
		System.out.println("======================================================\n");

		System.exit(runner.hasFailure() ? 1 : 0);
	}

	public static String getRunType() {
		if (GenerateVidRunner.class.getResource("GenerateVidRunner.class").getPath().contains(".jar"))
			return "JAR";
		else
			return "IDE";
	}
}
