// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	DeleteConsent(ctx context.Context, arg DeleteConsentParams) error
	GetConsent(ctx context.Context, arg GetConsentParams) (ConsentDetail, error)
	InsertConsentHistory(ctx context.Context, arg InsertConsentHistoryParams) error
	UpsertConsent(ctx context.Context, arg UpsertConsentParams) error
}

var _ Querier = (*Queries)(nil)
