## End point(s) relative URLs
getIdaCertificateUrl=/idauthentication/v1/internal/getCertificate
getPartnerCertificateUrl=/v1/partnermanager/partners/{partnerId}/certificate
putPartnerRegistrationUrl=/v1/partnermanager/partners
getPartnerCertURL=v1/identity/generatePartnerKeys
uploadCACertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadIntermediateCertificateUrl=/v1/partnermanager/partners/certificate/ca/upload
uploadPartnerCertificateUrl=/v1/partnermanager/partners/certificate/upload
uploadSignedCertificateUrl=v1/identity/updatePartnerCertificate
getKeyCloakTokenUrl = /auth/realms/master/protocol/openid-connect/token
masterSchemaURL=/v1/masterdata/idschema/latest
uploadIdaFirurl=v1/identity/uploadIDACertificate?certificateType=IDA_FIR&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
uploadPartnerurl=v1/identity/uploadIDACertificate?certificateType=PARTNER&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
uploadInternalurl=v1/identity/uploadIDACertificate?certificateType=INTERNAL&moduleName=$MODULENAME$&certsDir=$CERTSDIR$
authPolicyUrl=/v1/policymanager/policies
policyGroupUrl=/v1/policymanager/policies/group/new
publishPolicyurl=/v1/policymanager/policies/POLICYID/group/POLICYGROUPID/publish
clearCertificateURL=v1/identity/clearKeys?moduleName=$MODULENAME$&certsDir=$CERTSDIR$
validateSignatureUrl=v1/identity/validateSign

## As below are non changable values, move these out from properties file
appIdForCertificate=IDA
partnerrefId=PARTNER
internalrefId=INTERNAL
idaFirRefId=IDA-FIR

## As these will be based on mock identity schema regEx
passwordForAddIdentity=12341234_Aa

uinGenMaxLoopCount=20
uinGenDelayTime=10000
Delaytime=90000
