# values used to dynamically build the mock-identity-system AddIdentity request from its live schema
fullName=TEST_FULLNAME
givenName=TestGivenName
familyName=TestFamilyName
dateOfBirth=1996/01/01
gender=MLE
locality=Bangalore
region=KA
postalCode=560001
country=India
preferredLang=eng
locale=en
password=12341234_Aa
pin=545411
encodedPhoto=testphoto