apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak
spec:
  selector:
    istio: ingressgateway-internal
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.keycloakExternalHost }}
