apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-nginx-cm
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  nginx.conf: |-
    worker_processes  1;
    
    events {
      worker_connections  1024;
    }
    
    http {
      access_log /var/log/nginx/access1.log;
      error_log /var/log/nginx/error1.log;
      server {
        listen {{ .Values.oidc_ui.oidc_ui_port }};
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location /v1/esignet {
          proxy_pass         http://{{ .Values.oidc_ui.oidc_service_host }}/v1/esignet;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
        }
    
        location /.well-known/jwks.json {
          proxy_pass         http://{{ .Values.oidc_ui.oidc_service_host }}/v1/esignet/oauth/.well-known/jwks.json;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          types {
            text/plain log cer json txt;
          }
        }
    
        location /.well-known/openid-configuration {
          proxy_pass         http://{{ .Values.oidc_ui.oidc_service_host }}/v1/esignet/oidc/.well-known/openid-configuration;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          types {
            text/plain log cer json txt;
          }
        }
        
        location /.well-known/oauth-authorization-server {
          proxy_pass         http://{{ .Values.oidc_ui.oidc_service_host }}/v1/esignet/oauth/.well-known/oauth-authorization-server;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          types {
            text/plain log cer json txt;
          }
        }
    
        location /.well-known/openid-credential-issuer {
          proxy_pass         http://{{ .Values.oidc_ui.oidc_service_host }}/v1/esignet/vci/.well-known/openid-credential-issuer;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          types {
            text/plain log cer json txt;
          }
        }
        

        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }
{{- if .Values.oidc_ui.configmaps }}
  {{- range $cm_name, $cm_value := .Values.oidc_ui.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm_name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 8 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 8 }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 8 }}
  {{- end }}
data:
  {{- range $key, $value := $cm_value }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- end }}