{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - "*"
  gateways:
    {{ range $index, $service := .Values.istio.gateways }}
    - {{ .name }}
    {{ end }}
  http:
  - match:
      - uri:
          prefix: {{ .Values.istio.prefix }}
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    headers:
      request:
        set:
          x-forwarded-proto: https
      response:
        set:
          Cache-control: no-store
          Pragma: no-cache
          Strict-Transport-Security: max-age=31536000; includeSubDomains
          X-Frame-Options: SAMEORIGIN     
{{- end }}

