name: release-chart
on:
  push:
    branches:
      - master
      - 1.*
      - 0.*
      - develop
    paths:
      - 'helm/**'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.ACTION_PAT }}
          charts_dir: ./helm
          charts_url: https://mosip.github.io/mosip-helm
          repository: mosip-helm
          branch: gh-pages
