name: Tagging of repos

env:
  tag: v1.2.3

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Tag to be published'
        required: true
        default: 'v1.2.3'
        type: string
      BODY:
        description: 'Release body message'
        required: true
        default: 'Changes in this Release'
        type: string
      PRE_RELEASE:
        description: 'Pre-release? True/False'
        required: true
        default: False
        type: string
      DRAFT:
        description: 'Draft? True/False'
        required: false
        default: False
        type: string

jobs:
  tag-branch:
    uses: mosip/kattu/.github/workflows/tag.yml@master
    with:
      TAG: ${{ inputs.TAG }}
      BODY: ${{ inputs.BODY }}
      PRE_RELEASE: ${{ inputs.PRE_RELEASE }}
      DRAFT: ${{ inputs.DRAFT }}
